name: Test

on: ["push", "pull_request"]

jobs:
  test:
    name: Run units tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test with Coveralls
        run: npm run test:coveralls

      - name: Coveralls
        uses: coverallsapp/github-action@2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
